server:
  port: 8080
spring:
  application:
    name: airlineReservationSystem
  datasource:
    url: jdbc:mysql://localhost:3306/reservation
    username: root
    password: basma123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
